color: null
fieldLayouts:
  7701d0cf-dbdd-4910-910b-777082f7707c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ccbc1085-08a7-4493-b85d-84f8e6eddfc3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a193e81-87f0-40bf-a5a0-4a76a2920b18
        userCondition: null
handle: live
hasTitleField: true
icon: ''
name: Live
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
