altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  282c89dd-e0d4-47d8-93ba-d2a296d3e8e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d4f8c5de-2b0b-4c19-861b-c30b3b7c89dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1311b113-03e8-4e3b-a052-85134ec19072
        userCondition: null
fs: video
handle: video
name: Video
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
