isPublic: true
name: 'Public Schema'
scope:
  - 'sites.f255ef6d-0c55-4bdc-9ced-f610bbb3bed6:read' # $CRAFT_SITE_NAME
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'usergroups.everyone:read'
