columnSuffix: null
handle: pageContent
instructions: null
name: 'Page Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: f200013a-96be-4073-8522-84e1574099c7 # Simple
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  entryTypes:
    - 040da766-9122-4e00-bacc-8490dfa562f3 # Homepage
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
