defaultPlacement: end
enableVersioning: true
entryTypes:
  - 040da766-9122-4e00-bacc-8490dfa562f3 # Homepage
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f255ef6d-0c55-4bdc-9ced-f610bbb3bed6: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
