defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4e491a20-bdd5-42bf-97c9-b2afc09a2cad # Live
handle: live
maxAuthors: 1
name: Live
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f255ef6d-0c55-4bdc-9ced-f610bbb3bed6: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: sections/live.twig
    uriFormat: live
type: single
